### ISSUE TITLE
Please add a LICENSE file

### ISSUE THREAD

**Issue by ssokolow** [ShatReal/pcc#1]
Without an explicit license declaration, the interaction between "All Rights Reserved" and GitHub's Terms of Service basically means that people are allowed to view the code on GitHub and fork and edit it using GitHub's built-in editors, but not to download and run it.

https://choosealicense.com/ is the simplest way to fix that. Just find the license you want and there's a button to auto-generate a pull request to add the license file.

That said, given that you say Unlicense on the Itch.io page, I'll repeat what I [said](https://github.com/ShatReal/sutemo/issues/3) on your other project:

> I recommend switching Itch.io to CC0 since The Unlicense is [seriously flawed](https://softwareengineering.stackexchange.com/q/147111/35055) (it's invalid in some jurisdictions, self-contradictory, and doesn't address privileges that need to be explicitly disclaimed to protect people from being sued by your heirs, such as [moral rights](https://en.wikipedia.org/wiki/Moral_rights)). 
>
> For example, Germany doesn't have a provision in the law for putting things in the public domain prematurely, and retroactively grants creators the right to sue over privileges that didn't exist at the time unless they head that off. This [anaylsis of the CC0](https://rd-alliance.org/sites/default/files/cc0-analysis-kreuzer.pdf) explains how it solves those problems.
>
> I'd need to double-check, but I believe the "self-contradictory" part is that the Unlicense's phrasing pretends that "public domain" is a type of license, rather than the state of no longer having the power to apply a license. Judges and lawyers don't like it when you drop your key into a smelter and then lock your deadbolt without acknowledging that you no longer have a key.

**Comment by ShatReal** [comment]
Thank you, I have added a license file.
